---
- hosts: ansible
  
  tasks:
    - name: Create Docker Image
      command: docker build -t regapp:latest .
      args: 
        chdir: /opt/docker
    
    - name: Create tag to push image onto Dockerhub
      command: docker tag regapp:latest sinhhuy1309/regapp:latest

    - name: push Docker image
      command: docker push sinhhuy1309/regapp:latest